### PR TITLE
41-create-section-about-sdlc

### PR DESCRIPTION
**Pull request by focadiz**
Work in progress

### CODE REVIEW

**Comment by focadiz** [comment]
Hey Juan(es), the document is almost ready, a couple of ToDos there but it would not change that much.

Please let me know what you both think.

**Comment by focadiz** [comment]
For further discussion:
Should Names in Design Center be Human friendly? The Audience for Design Center is Architects and since we plan to automate the sync between Design Center, Studio and Exchange, probably matching with Maven would be more functional even though I think Human Friendly should be the norm.
What about Exchange? The audience here may not be very technical so they are more focused on the functionality side and also on the process side so my suggestion is to make it Human friendly.
My last question is around the table above, is this the right document? Initially I wanted to describe the naming convention only but somehow I ended up creating that table that may include the asset in Exchange and the API in Design Center.
Initially I thought about using the artifact id in the cloudhub domain but we have a 42 characters restriction and RideXpress already used 10 so I kept it short and I liked it. Also thought about using the api layer as part of the url but didn't find any value in doing so, keeping the API url simple seems more adequate to me. The layers are more relevant at the Maven and the Exchange level.

**Comment by JuanCBasso** [comment]
We need to consider for section 7.1 in the domain name, the changes that can imply using CH 2.0.
And we need to check how we are going to identify the env via the URL setup.

**Comment by focadiz** [comment]
@JuanCBasso I fixed the document based on your feedback

**Comment by focadiz** [comment]
@JuanCBasso / @jony404 Can I have more feedback please?

**Comment by jony404** [comment]
A few suggestions:
do we really need to follow HATEOAS? Looks like we might spend more time in the development using this convention. My suggestion is to keep it as simple as possible, sounds like HATEOAS use case is more for automated systems or business process managers.

For flow names ca we include the keyword Flow/Subflow at the end? That way we know a flow ref is calling what from the main flow UI and we easier identify where to add error handling.  This is only for not autogenerated flows.

**Comment by focadiz** [comment]
Regarding HATEOAS, it's a fair assessment, Initially I thought about keeping it simple but then I thought, if the long term goal is to use more industry standards, we would need to release v2 because it would not be backward compatible, but I like it though, I'll change it.

Regarding the flow names, sounds good to me, I'll fix it.

**Comment by focadiz** [comment]
Done

**Comment by jony404** [comment]
Just some information I found on the matter. 
When are HATEOAS links not useful?
When the system is too narrow
When front-end and back-end are developed by the same person (in monorepo – when code for multiple projects is stored in the same repository)
When the client API does not understand the intent

Disadvantages of HATEOAS
The REST application constraint has no established standards. As a result, the HATEOAS libraries carry various representations of links. With differing syntax, similar outputs may be achieved, but the overall build of the API can be more difficult to implement due to varying link representation. 

Higher latency and more bandwidth – the downsides affect mostly users of mobile devices. Payloads grow with the growing number of links provided as a response. To reduce the negative impact on equipment with lower latency than PCs, APIs developed for mobile devices should carry fewer payloads.

No library support. Before reaching great popularity, HATEOAS has already been outrun by other approaches (e.g. GraphQL). As a result, finding suitable libraries for every programming language may be challenging.

**Review by jony404 — APPROVED** [review]

**Pull request merged**
